### ISSUE TITLE
Handling individual message frames 

### ISSUE THREAD

**Issue by daveyarwood** [daveyarwood/ezzmq#7]
The default ezzmq behavior is to keep receiving the frames of multi-part messages until there are none left to receive. 

It occurred to me, though, that sometimes it might be preferable to start processing individual frames as they are received, e.g. if the message could have a huge number of frames and you don't want to wait until you receive them all before you start doing work.

Perhaps `receive-frame` and `send-frame` functions could be useful for greater flexibility. `send-frame` would need to take options, so the caller could specify whether the frame being sent is the final frame of a message, otherwise the default behavior would be to send with the SENDMORE flag. Conveniently, calling `receive-msg` after a bunch of `receive-frame` calls would receive the rest of the message frames all at once.

Another thought: a lazy sequence abstraction, so that frames could be received lazily as the seq is consumed, or realized all at once. This could be nice because you could do things like use `doseq` over the frame sequence and process each message as it is received.

**Comment by mastersign** [comment]
The zeromq protocol dictates, that all frames of a mutipart message must be received from the network  and buffered in memory before handing them to the API caller. And while sending, it states that all frames of a multipart message must be handed to the socket by the API caller, again, buffered in memory, before they actually get sent over the wire. This is necessary for the atomic nature of messages.

Therefore, representing the frames of a multipart message as a collection of byte arrays is pretty senseful. Because, at the interface of the JeroMQ API, the frame sequence of a multipart message must be realized anyways.

If you want to transfer larger amounts of data with zeromq than you are comfortable putting in memory, you need to send multiple messages and not one multipart message (streaming). In that case you have to care for the integrity of the total data yourself.

**Comment by daveyarwood** [comment]
Thanks for the explanation -- I didn't know it worked that way!
